# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04ad0950971acdf36ac8a11154f1cd56488e59823d0847a0e3e9e0047447155e396070527be9dadbcb2e8635b598dd08afc065fed76359632943d396b607eead

test:
  secret_key_base: b9ad67ec1c508a93263d64905c2eff46379392e2e1c308dd6a998881b42fcc8570faa8c11a953cce4e916dd5e320a08832fc50c462a1092375bf13cc541ea59c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
